<?php include 'inc/header.phtml' ?>

<body>

    <div id="page">

        <?php include 'inc/navbar.phtml' ?>

        <section id="home" class="video-hero">
            <div class="overlay"></div>
            <div class="display-t display-t2 text-center">
                <div class="display-tc display-tc2">
                    <div class="container">
                        <div class="col-md-12 col-md-offset-0">
                            <div class="animate-box">
                                <h2 id="titulo"></h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="colorlib-work-featured">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-justify animate-box">
                        <p>La p&aacute;gina que est&aacute;s buscando no existe! Si crees que este es un error nuestro envianos un email! Gracias!</p>
                    </div>
                </div>
            </div>
        </div>

        <?php include 'inc/footer.phtml' ?>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>

    <script src="/src/js/jquery.min.js"></script>
    <script src="/src/js/jquery.easing.1.3.js"></script>
    <script src="/src/js/bootstrap.min.js"></script>
    <script src="/src/js/jquery.waypoints.min.js"></script>
    <script src="/src/js/main.js"></script>
    <script>
        new Typed('#titulo', {
            strings: ['Error'],
            typeSpeed: 100,
            showCursor: false,
            startDelay: 200
        })
    </script>

</body>

</html>
