<?php include 'inc/header.phtml' ?>

<body>

    <div id="page">

        <?php include 'inc/navbar.phtml' ?>

        <section id="home" class="video-hero" style="height: 700px;" data-section="home">
            <div class="overlay"></div>
            <a></a>
            <div class="display-t text-center">
                <div class="display-tc">
                    <div class="container">
                        <div class="col-md-12 col-md-offset-0">
                            <div class="animate-box">
                                <h2 id="titulo"></h2>
                                <p id="subtitulo"></p>
                                <p><a href="/servicios" class="btn btn-primary btn-lg btn-custom">Ver servicios</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="colorlib-featured">
            <div class="row animate-box">
                <div class="featured-wrap">
                    <div class="owl-carousel">
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/escritorio-1.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/escritorio-2.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/escritorio-3.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-intro">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box">
                        <h2>El momento es ahora!</h2>
                        <p class="blockquote-reverse">"Si no se implementan [los avances tecnológicos] de una manera más
                            amplia, una desigualdad industrial podría emerger, creando un pequeño grupo de líderes industriales
                            altamente productivos y dejando rezagada al resto de la economía".<br>
                            (Foro Econ&oacute;mico Mundial en Davos, Enero 2018)</p>
                        <p>Por eso, nuestro objetivo es lograr que el mayor n&uacute;mero de organizaciones se suban a la ola
                            de los avances del siglo XXI, alcanzando su potencial y logrando sus sue&ntilde;os.</p>
                    </div>
                </div>
            </div>
            <br />
        </div>

        <div class="colorlib-services colorlib-bg-white">
            <div class="container">
                <!-- <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box">
                        <h2>C&oacute;mo te ayudamos</h2>
                    </div>
                </div> -->
                <div class="row">
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
                            <span class="icon">
                                <i class="icon-browser"></i>
                            </span>
                            <div class="desc">
                                <h3>Gesti&oacute;n eficaz</h3>
                                <p><strong>Optimiz&aacute;</strong> los procesos de tu negocio.
                                    <strong>Mejor&aacute;</strong> los tiempos de respuesta para tus clientes.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
                            <span class="icon">
                                <i class="icon-download"></i>
                            </span>
                            <div class="desc">
                                <h3>Accesible</h3>
                                <p>Desde <strong>cualquier</strong> dispositivo, lugar y momento ten&eacute; a mano
                                    el
                                    estado de tu empresa.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
                            <span class="icon">
                                <i class="icon-adjustments"></i>
                            </span>
                            <div class="desc">
                                <h3>A medida</h3>
                                <p>Un sistema inform&aacute;tico que <strong>s&iacute;</strong> hace lo que necesitas.
                                    Lo
                                    adaptamos a tus procesos.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
                            <span class="icon">
                                <i class="icon-video"></i>
                            </span>
                            <div class="desc">
                                <h3>Capacitaci&oacute;n</h3>
                                <p>Recursos disponibles. Nos encargamos de <strong>capacitarte</strong> "in situ" si
                                    hace
                                    falta.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
                            <span class="icon">
                                <i class="icon-gears"></i>
                            </span>
                            <div class="desc">
                                <h3>Ayuda y Soporte</h3>
                                <p>Nuestro staff preparado est&aacute; listo para <strong>ayudarte</strong> y responder
                                    tus
                                    dudas.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
                            <span class="icon">
                                <i class="icon-layers"></i>
                            </span>
                            <div class="desc">
                                <h3>Infinitas caracter&iacute;sticas</h3>
                                <p>Pens&aacute;s que no tenemos lo que necesit&aacute;s? <strong>Lo hacemos!</strong>.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center animate-box">
                        <p>
                            <a href="/servicios" class="btn btn-lg btn-primary with-arrow">M&aacute;s detalles<i class="icon-arrow-right3"></i></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div id="colorlib-subscribe" class="colorlib-subscribe">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 text-center colorlib-heading animate-box fadeInUp animated-fast">
                        <h2>Nuestros Partners</h2>
                    </div>
                </div>
                <div class="row animate-box fadeInUp animated-fast">
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/src/images/afip-partner.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/src/images/aws-partner.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/src/images/vue-partner.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/src/images/intel-partner.svg" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/src/images/php-partner.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/src/images/mercadopago-partner.png" class="img-responsive">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php include 'inc/footer.phtml' ?>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
    <script src="/src/js/jquery.min.js"></script>
    <script src="/src/js/jquery.easing.1.3.js"></script>
    <script src="/src/js/bootstrap.min.js"></script>
    <script src="/src/js/jquery.waypoints.min.js"></script>
    <script src="/src/js/owl.carousel.min.js"></script>
    <script src="/src/js/main.js"></script>
    <script>
        $(document).ready(function() {
            new Typed('#titulo', {
                strings: ['Sac&aacute; provecho de los avances tecnol&oacute;gicos!'],
                typeSpeed: 75,
                showCursor: false,
                startDelay: 200,
                onComplete: (self) => {
                    new Typed('#subtitulo', {
                        strings: ['Lo hacemos con vos.', 'Te acompa&ntilde;amos.', 'Es nuestra pasi&oacute;n.'],
                        typeSpeed: 75,
                        startDelay: 200,
                        showCursor: false,
                        backSpeed: 50,
                        loop: true
                    })
                },
            })

            var owl = $('.owl-carousel');
            owl.owlCarousel({
                animateOut: 'fadeOut',
                animateIn: 'fadeIn',
                autoplay: true,
                items: 1,
                loop: true,
                margin: 0,
                responsiveClass: true,
                nav: false,
                dots: true,
                autoplayHoverPause: false,
                smartSpeed: 500,
                navText: [
                    "<i class='icon-arrow-left3 owl-direction'></i>",
                    "<i class='icon-arrow-right3 owl-direction'></i>"
                ]
            });
        });
    </script>
</body>

</html>
