<?php include 'inc/header.phtml' ?>

    <body>

    <div id="page">

        <?php include 'inc/navbar.phtml' ?>

        <section id="home" class="video-hero" style="height: 700px;" data-section="home">
            <div class="overlay"></div>
            <a></a>
            <div class="display-t text-center">
                <div class="display-tc">
                    <div class="container">
                        <div class="col-md-12 col-md-offset-0">
                            <div class="animate-box">
                                <h2>Tomale ventaja a la competencia</h2>
                                <p>con la tecnolog&iacute;a de Proycer</p>
                                <p><a href="#servicios" class="btn btn-primary btn-lg btn-custom">Ver servicios</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="colorlib-featured">
            <div class="row animate-box">
                <div class="featured-wrap">
                    <div class="owl-carousel">
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/assets/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/assets/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/assets/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-work-featured colorlib-bg-white" id="servicios">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box fadeInUp animated-fast">
                        <h2>Nuestros servicios</h2>
                    </div>
                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="https://wisp.proycer.com.ar">Proycer Wisp&trade;</a></h2>
                            <p class="admin text-center"><span>ISP's</span></p>
                            <p>Sistema de Gesti&oacute;n y Administraci&oacute;n para empresas proveedoras de internet,
                                televisi&oacute;n y/o telefon&iacute;a.</p>
                            <ul>
                                <li>Clientes</li>
                                <li>Facturas</li>
                                <li>Servicios</li>
                                <li>Instalaciones</li>
                                <li>Pagos online</li>
                                <li>Y m&aacute;s..</li>
                            </ul>
                            <p><a href="#" class="btn btn-primary btn-outline with-arrow">Ver m&aacute;s<i
                                            class="icon-arrow-right3"></i></a></p>
                        </article>
                    </div>
                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="#">Proycer Time&trade;</a></h2>
                            <p class="admin text-center"><span>Turnos</span></p>
                            <p>Sistema de Gesti&oacute;n y Administraci&oacute;n del tiempo, directorio y citas para
                                turnos de consultorios.</p>
                            <ul>
                                <li>Calendario</li>
                                <li>Citas</li>
                                <li>Clientes</li>
                                <li>Directorio</li>
                                <li>Proveedores</li>
                                <li>Y m&aacute;s..</li>
                            </ul>
                            <p><a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i
                                            class="icon-arrow-right3"></i></a></p>
                        </article>
                    </div>
                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="#">Proycer Store&trade;</a></h2>
                            <p class="admin text-center"><span>Tienda</span></p>
                            <p>Sistema de Gesti&oacute;n y Administraci&oacute;n de ventas y log&iacute;stica para tu
                                comercio. Ideal retail.</p>
                            <ul>
                                <li>Clientes</li>
                                <li>Productos</li>
                                <li>Stock</li>
                                <li>Ventas</li>
                                <li>Facturaci&oacute;n Afip</li>
                                <li>Y m&aacute;s..</li>
                            </ul>
                            <p><a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i
                                            class="icon-arrow-right3"></i></a></p>
                        </article>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-intro">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box">
                        <h2>El momento es ahora!</h2>
                        <p class="blockquote-reverse">"Si no se implementan [los avances tecnológicos] de una manera más
                            amplia,
                            una desigualdad industrial podría emerger, creando un pequeño grupo de líderes industriales
                            altamente productivos y dejando rezagada al resto de la economía".<br>
                            (Foro Econ&oacute;mico Mundial en Davos, Enero 2018)</p>
                        <p>Por eso, nuestro objetivo es lograr que el mayor n&uacute;mero de organizaciones se suban a
                            la
                            ola
                            de los avances del siglo XXI, alcanzando su potencial y logrando sus sue&ntilde;os.</p>
                    </div>
                </div>
            </div>
        </div>

        <div id="colorlib-subscribe" class="colorlib-subscribe">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 text-center colorlib-heading animate-box fadeInUp animated-fast">
                        <h2>Nuestros Partners</h2>
                    </div>
                </div>
                <div class="row animate-box fadeInUp animated-fast">
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/logo_afip.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/MikroTik_logo.svg" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/1200px-Amazon_Web_Services_Logo.svg.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/Intel-logo.svg" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/720px-Arduino_Logo.svg.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/mercadopago.png" class="img-responsive">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php include 'inc/footer.phtml' ?>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>

    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/jquery.easing.1.3.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.waypoints.min.js"></script>
    <script src="/assets/js/jquery.stellar.min.js"></script>
    <script src="/assets/js/owl.carousel.min.js"></script>
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="/assets/js/magnific-popup-options.js"></script>
    <script src="/assets/js/jquery.countTo.js"></script>
    <script src="/assets/js/main.js"></script>

    </body>
</html>