<?php include 'inc/header.phtml' ?>

    <body>

    <div id="page">

        <?php include 'inc/navbar.phtml' ?>

        <section id="home" class="video-hero" style="height: 700px;" data-section="home">
            <div class="overlay"></div>
            <a></a>
            <div class="display-t text-center">
                <div class="display-tc">
                    <div class="container">
                        <div class="col-md-12 col-md-offset-0">
                            <div class="animate-box">
                                <h2>Tom&aacute; provecho de los avances <br />tecnol&oacute;gicos.</h2>
                                <p>Te acompa&ntilde;amos</p>
                                <p><a href="/servicios" class="btn btn-primary btn-lg btn-custom">Ver servicios</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="colorlib-featured">
            <div class="row animate-box">
                <div class="featured-wrap">
                    <div class="owl-carousel">
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/assets/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/assets/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/assets/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-intro">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box">
                        <h2>El momento es ahora!</h2>
                        <p class="blockquote-reverse">"Si no se implementan [los avances tecnológicos] de una manera más
                            amplia,
                            una desigualdad industrial podría emerger, creando un pequeño grupo de líderes industriales
                            altamente productivos y dejando rezagada al resto de la economía".<br>
                            (Foro Econ&oacute;mico Mundial en Davos, Enero 2018)</p>
                        <p>Por eso, nuestro objetivo es lograr que el mayor n&uacute;mero de organizaciones se suban a
                            la
                            ola
                            de los avances del siglo XXI, alcanzando su potencial y logrando sus sue&ntilde;os.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-services colorlib-bg-white">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
							<span class="icon">
								<i class="icon-browser"></i>
							</span>
                            <div class="desc">
                                <h3>Gesti&oacute;n eficaz</h3>
                                <p><strong>Optimiz&aacute;</strong> los procesos de tu negocio.
                                    <strong>Mejor&aacute;</strong> los tiempos de respuesta para tus clientes.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
							<span class="icon">
								<i class="icon-download"></i>
							</span>
                            <div class="desc">
                                <h3>Accesible</h3>
                                <p>Desde <strong>cualquier</strong> dispositivo, lugar y momento ten&eacute; a mano
                                    el
                                    estado de tu empresa.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
							<span class="icon">
								<i class="icon-adjustments"></i>
							</span>
                            <div class="desc">
                                <h3>A medida</h3>
                                <p>Un sistema inform&aacute;tico que <strong>s&iacute;</strong> hace lo que necesitas.
                                    Lo
                                    adaptamos a tus procesos.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
							<span class="icon">
								<i class="icon-video"></i>
							</span>
                            <div class="desc">
                                <h3>Capacitaci&oacute;n</h3>
                                <p>Recursos disponibles. Nos encargamos de <strong>capacitarte</strong> "in situ" si
                                    hace
                                    falta.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
							<span class="icon">
								<i class="icon-gears"></i>
							</span>
                            <div class="desc">
                                <h3>Ayuda y Soporte</h3>
                                <p>Nuestro staff preparado est&aacute; listo para <strong>ayudarte</strong> y responder
                                    tus
                                    dudas.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 text-center animate-box">
                        <div class="services">
							<span class="icon">
								<i class="icon-layers"></i>
							</span>
                            <div class="desc">
                                <h3>Infinitas caracter&iacute;sticas</h3>
                                <p>Pens&aacute;s que no tenemos lo que necesit&aacute;s? <strong>Lo hacemos!</strong>.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="colorlib-subscribe" class="colorlib-subscribe">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 text-center colorlib-heading animate-box fadeInUp animated-fast">
                        <h2>Nuestros Partners</h2>
                    </div>
                </div>
                <div class="row animate-box fadeInUp animated-fast">
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/logo_afip.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/MikroTik_logo.svg" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/1200px-Amazon_Web_Services_Logo.svg.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/Intel-logo.svg" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/720px-Arduino_Logo.svg.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-2 animate-box fadeInUp animated-fast">
                        <div class="staff-entry">
                            <img src="/assets/images/mercadopago.png" class="img-responsive">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php include 'inc/footer.phtml' ?>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>

    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/jquery.easing.1.3.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.waypoints.min.js"></script>
    <script src="/assets/js/jquery.stellar.min.js"></script>
    <script src="/assets/js/owl.carousel.min.js"></script>
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="/assets/js/magnific-popup-options.js"></script>
    <script src="/assets/js/jquery.countTo.js"></script>
    <script src="/assets/js/main.js"></script>

    </body>
</html>
