<footer id="colorlib-footer">
    <div class="copy">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>
                        Copyright &copy; <?= date('Y') ?>
                        All rights reserved | Modified template made by Colorlib
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

