<!DOCTYPE HTML>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $title ?> | Proycer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Tomale ventaja a la competencia con la tecnolog&iacute;a de Proycer. Gesti&oacute;n eficaz, accesible y a medida." />
    <meta name="keywords" content="sistema, gestion, erp, crm, neuquen, software" />
    <meta name="author" content="John Esteban Astete Arambarri" />

    <link rel="apple-touch-icon" sizes="180x180" href="/src/images/apple-touch-icon.png?v=m2RYprzqMB">
    <link rel="icon" type="image/png" sizes="32x32" href="/src/images/favicon-32x32.png?v=m2RYprzqMB">
    <link rel="icon" type="image/png" sizes="16x16" href="/src/images/favicon-16x16.png?v=m2RYprzqMB">
    <link rel="manifest" href="/src/images/site.webmanifest?v=m2RYprzqMB">
    <link rel="mask-icon" href="/src/images/safari-pinned-tab.svg?v=m2RYprzqMB" color="#5bbad5">
    <link rel="shortcut icon" href="/src/images/favicon.ico?v=m2RYprzqMB">
    <meta name="apple-mobile-web-app-title" content="Proycer">
    <meta name="application-name" content="Proycer">
    <meta name="msapplication-TileColor" content="#9f00a7">
    <meta name="msapplication-config" content="/src/images/browserconfig.xml?v=m2RYprzqMB">
    <meta name="theme-color" content="#ffffff">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400" rel="stylesheet">

    <link rel="stylesheet" href="/src/css/style.min.css">

    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="/src/js/respond.min.js"></script>
    <![endif]-->

</head>
