<!DOCTYPE HTML>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= $title ?> | Proycer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Tomale ventaja a la competencia con la tecnolog&iacute;a de Proycer. Gesti&oacute;n eficaz, accesible y a medida." />
    <meta name="keywords" content="sistema, gestion, erp, crm, neuquen, software" />
    <meta name="author" content="John Esteban Astete Arambarri" />

    <link href="/src/images/favicon_proycer32.png" rel="icon" />

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400" rel="stylesheet">

    <link rel="stylesheet" href="/src/css/animate.css">
    <link rel="stylesheet" href="/src/css/icomoon.css">
    <link rel="stylesheet" href="/src/css/bootstrap.css">
    <link rel="stylesheet" href="/src/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/src/css/owl.theme.default.min.css">

    <link rel="stylesheet" href="/src/css/style.css">

    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="/src/js/respond.min.js"></script>
    <![endif]-->

</head>
