<nav class="colorlib-nav" role="navigation">
    <div class="top-menu">
        <div class="container">
            <div class="row animate-box">
                <div class="col-md-2">
                    <div id="colorlib-logo">
                        <a href="/">
                            <img src="/src/images/proycer_logo_120p.png" alt="logo_proycer">
                        </a>
                    </div>
                </div>
                <div class="col-md-10 text-right menu-1">
                    <ul>
                        <li<?= $request == '/' ? ' class="active"' : ''?>><a href="/">Inicio</a></li>
                        <li<?= strpos($request, 'servicios') != false ? ' class="active"' : ''?>><a href="/servicios">Servicios</a></li>
                        <li<?= strpos($request, 'nosotros') != false ? ' class="active"' : ''?>><a href="/nosotros">Nosotros</a></li>
                        <li<?= strpos($request, 'contacto') != false ? ' class="active"' : ''?>><a href="/contacto">Contacto</a></li>
                        <li<?= strpos($request, 'autogestion') != false ? ' class="active"' : ''?>><a href="https://crm.proycer.com.ar">Autogesti&oacute;n</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>
