<?php include __DIR__ . '/../inc/header.phtml' ?>

<body>

    <div id="page">

        <?php include __DIR__ . '/../inc/navbar.phtml' ?>

        <section id="home" class="video-hero">
            <div class="overlay"></div>
            <div class="display-t display-t2 text-center">
                <div class="display-tc display-tc2">
                    <div class="container">
                        <div class="col-md-12 col-md-offset-0">
                            <div class="animate-box">
                                <h2 id="titulo"></h2>
                                <br /><br />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="colorlib-featured">
            <div class="row animate-box">
                <div class="featured-wrap">
                    <div class="owl-carousel">
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/wisp-tablero.jpg" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-work-featured colorlib-bg-white">
            <div class="container">
                <div class="row mobile-wrap">
                    <div class="col-md-5 animate-box fadeInUp animated-fast">
                        <div class="mobile-img" style="background-image: url(images/mobile-2.jpg);"></div>
                    </div>
                    <div class="col-md-7 animate-box fadeInUp animated-fast">
                        <div class="desc">
                            <h2>Real template creation</h2>
                            <div class="features">
                                <span class="icon"><i class="icon-lightbulb"></i></span>
                                <div class="f-desc">
                                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                                </div>
                            </div>
                            <div class="features">
                                <span class="icon"><i class="icon-circle-compass"></i></span>
                                <div class="f-desc">
                                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name</p>
                                </div>
                            </div>
                            <div class="features">
                                <span class="icon"><i class="icon-beaker"></i></span>
                                <div class="f-desc">
                                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                                </div>
                            </div>
                            <p><a href="#" class="btn btn-primary btn-outline with-arrow">Start collaborating <i class="icon-arrow-right3"></i></a></p>
                        </div>
                    </div>
                </div>
                <div class="row mobile-wrap">
                    <div class="col-md-5 col-md-push-7 animate-box fadeInUp animated-fast">
                        <div class="mobile-img" style="background-image: url(images/mobile-1.jpg);"></div>
                    </div>
                    <div class="col-md-7 col-md-pull-5 animate-box fadeInUp animated-fast">
                        <div class="desc">
                            <h2>Finish template creation</h2>
                            <div class="features">
                                <span class="icon"><i class="icon-lightbulb"></i></span>
                                <div class="f-desc">
                                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                                </div>
                            </div>
                            <div class="features">
                                <span class="icon"><i class="icon-circle-compass"></i></span>
                                <div class="f-desc">
                                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name</p>
                                </div>
                            </div>
                            <div class="features">
                                <span class="icon"><i class="icon-beaker"></i></span>
                                <div class="f-desc">
                                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                                </div>
                            </div>
                            <p><a href="#" class="btn btn-primary btn-outline with-arrow">Start collaborating <i class="icon-arrow-right3"></i></a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-pricing">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box fadeInUp animated-fast">
                        <h2>Pricing</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 text-center animate-box fadeInUp animated-fast">
                        <div class="pricing">
                            <h2 class="pricing-heading">Inicio</h2>
                            <div class="price"><sup class="currency">$</sup>1000<small>per month</small></div>
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                            <p><a href="#" class="btn btn-primary">Select Plan</a></p>
                        </div>
                    </div>
                    <div class="col-md-3 text-center animate-box fadeInUp animated-fast">
                        <div class="pricing">
                            <h2 class="pricing-heading">Basico</h2>
                            <div class="price"><sup class="currency">$</sup>2000<small>per month</small></div>
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                            <p><a href="#" class="btn btn-primary">Select Plan</a></p>
                        </div>
                    </div>
                    <div class="col-md-3 text-center animate-box fadeInUp animated-fast">
                        <div class="pricing">
                            <h2 class="pricing-heading">Pro</h2>
                            <div class="price"><sup class="currency">$</sup>3000<small>per month</small></div>
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                            <p><a href="#" class="btn btn-primary">Select Plan</a></p>
                        </div>
                    </div>
                    <div class="col-md-3 text-center animate-box fadeInUp animated-fast">
                        <div class="pricing">
                            <h2 class="pricing-heading">Ilimitado</h2>
                            <div class="price"><sup class="currency">$</sup>4000<small>per month</small></div>
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                            <p><a href="#" class="btn btn-primary">Select Plan</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php include __DIR__ . '/../inc/footer.phtml' ?>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>

    <script src="/src/js/jquery.min.js"></script>
    <script src="/src/js/jquery.easing.1.3.js"></script>
    <script src="/src/js/bootstrap.min.js"></script>
    <script src="/src/js/owl.carousel.min.js"></script>
    <script src="/src/js/jquery.waypoints.min.js"></script>
    <script src="/src/js/main.js"></script>
    <script>
        $(document).ready(function() {
            var owl = $('.owl-carousel');
            owl.owlCarousel({
                animateOut: 'fadeOut',
                animateIn: 'fadeIn',
                autoplay: true,
                items: 1,
                loop: true,
                margin: 0,
                responsiveClass: true,
                nav: false,
                dots: true,
                autoplayHoverPause: true,
                smartSpeed: 500,
                navText: [
                    "<i class='icon-arrow-left3 owl-direction'></i>",
                    "<i class='icon-arrow-right3 owl-direction'></i>"
                ]
            });

            new Typed('#titulo', {
                strings: ['Proycer Wisp'],
                typeSpeed: 100,
                showCursor: false,
                startDelay: 200
            })
        });
    </script>
</body>

</html>
