<?php include __DIR__ . '/../inc/header.phtml' ?>

    <body>

    <div id="page">

        <?php include __DIR__ . '/../inc/navbar.phtml' ?>

        <section id="home" class="video-hero">
            <div class="overlay"></div>
            <div class="display-t display-t2 text-center">
                <div class="display-tc display-tc2">
                    <div class="container">
                        <div class="col-md-12 col-md-offset-0">
                            <div class="animate-box">
                                <h2><?= $title ?></h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</section>

        <div class="colorlib-work-featured" id="servicios">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="https://wisp.proycer.com.ar">Proycer Wisp&trade;</a></h2>
                            <p class="admin text-center"><span>ISP's</span></p>
                            <p>Sistema de Gesti&oacute;n y Administraci&oacute;n para empresas proveedoras de internet,
                                televisi&oacute;n y/o telefon&iacute;a.</p>
                            <!-- <ul>
                                <li>Clientes</li>
                                <li>Facturas</li>
                                <li>Servicios</li>
                                <li>Instalaciones</li>
                                <li>Pagos online</li>
                                <li>Y m&aacute;s..</li>
                            </ul> -->
                            <p>
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>
                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="#">Proycer Help&trade;</a></h2>
                            <p class="admin text-center"><span>Soporte</span></p>
                            <p>Sistema de Tickets y Soporte para tus servicios o proyectos. M&aacute;s cerca de tus clientes.</p>
                            <!-- <ul>
                                <li>Clientes</li>
                                <li>Servicios</li>
                                <li>Tickets</li>
                                <li>Mensajer&iacute;a</li>
                                <li>Y m&aacute;s..</li>
                            </ul> -->
                            <p>
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>
                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="#">Proycer Time&trade;</a></h2>
                            <p class="admin text-center"><span>Turnos</span></p>
                            <p>Sistema de Gesti&oacute;n y Administraci&oacute;n de tiempo, directorio y citas para
                                turnos de consultorios.</p>
                            <!-- <ul>
                                <li>Calendario</li>
                                <li>Citas</li>
                                <li>Clientes</li>
                                <li>Directorio</li>
                                <li>Proveedores</li>
                                <li>Y m&aacute;s..</li>
                            </ul> -->
                            <p>
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>

                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="#">Proycer Work&trade;</a></h2>
                            <p class="admin text-center"><span>Partes de Servicio</span></p>
                            <p>Sistema de Gesti&oacute;n y Administraci&oacute;n de &oacute;rdenes de servicios, tareas y/o trabajos.</p>
                            <!-- <ul>
                                <li>Clientes</li>
                                <li>Productos</li>
                                <li>Stock</li>
                                <li>Ventas</li>
                                <li>Facturaci&oacute;n Afip</li>
                                <li>Y m&aacute;s..</li>
                            </ul> -->
                            <p>
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>

                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="#">Proycer Store&trade;</a></h2>
                            <p class="admin text-center"><span>Tienda</span></p>
                            <p>Sistema de Gesti&oacute;n y Administraci&oacute;n de ventas y log&iacute;stica para tu
                                comercio. Ideal retail.</p>
                            <!-- <ul>
                                <li>Clientes</li>
                                <li>Productos</li>
                                <li>Stock</li>
                                <li>Ventas</li>
                                <li>Facturaci&oacute;n Afip</li>
                                <li>Y m&aacute;s..</li>
                            </ul> -->
                            <p>
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>

                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center"><a href="#">Proycer Web&trade;</a></h2>
                            <p class="admin text-center"><span>Sitio Web</span></p>
                            <p>Sistema Web autogestionable. Excelente para mantener tu sitio actualizado a bajo costo.</p>
                            <!-- <ul>
                                <li>Clientes</li>
                                <li>Productos</li>
                                <li>Stock</li>
                                <li>Ventas</li>
                                <li>Facturaci&oacute;n Afip</li>
                                <li>Y m&aacute;s..</li>
                            </ul> -->
                            <p>
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>
                </div>
            </div>
        </div>

        <div id="colorlib-subscribe" class="colorlib-subscribe">
			<div class="overlay"></div>
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center colorlib-heading animate-box fadeInUp animated-fast">
						<h2>Empez&aacute; a vender m&aacute;s y mejor ;)</h2>
						<p>Dejanos tu email y te contactamos para guiarte sin compromiso</p>
					</div>
				</div>
				<div class="row animate-box fadeInUp animated-fast">
					<div class="col-md-6 col-md-offset-3">
						<div class="row">
							<div class="col-md-12">
							<form class="form-inline qbstp-header-subscribe">
								<div class="col-three-forth">
									<div class="form-group">
										<input type="email" class="form-control" id="email" placeholder="Escrib&iacute; tu email" required>
									</div>
								</div>
								<div class="col-one-third">
									<div class="form-group">
										<button type="submit" class="btn btn-primary">Enviar</button>
									</div>
								</div>
							</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

        <?php include __DIR__ . '/../inc/footer.phtml' ?>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>

    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/jquery.easing.1.3.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/jquery.waypoints.min.js"></script>
    <script src="/assets/js/jquery.stellar.min.js"></script>
    <script src="/assets/js/owl.carousel.min.js"></script>
    <script src="/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="/assets/js/magnific-popup-options.js"></script>
    <script src="/assets/js/jquery.countTo.js"></script>
    <script src="/assets/js/main.js"></script>

    </body>
</html>
