<?php include __DIR__ . '/../inc/header.phtml' ?>

<body>

    <div id="page">

        <?php include __DIR__ . '/../inc/navbar.phtml' ?>

        <section id="home" class="video-hero">
            <div class="overlay"></div>
            <div class="display-t display-t2 text-center">
                <div class="display-tc display-tc2">
                    <div class="container">
                        <div class="col-md-12 col-md-offset-0">
                            <div class="animate-box">
                                <h2 id="titulo"></h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="colorlib-work-featured">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-justify animate-box">
                        <p>Los <Strong>sistemas de gesti&oacute;n en plataforma web</Strong> permiten el acceso a tus datos en <strong>cualquier dispositivo</strong>, desde <strong>cualquier lugar</strong> y en <strong>cualquier momento</strong>.
                            Evita las grandes inversiones de hardware y software, concentr&aacute;ndote en las funcionalidades necesarias, sin preocuparte de todo lo demás. <strong>S&oacute;lo pag&aacute;s por lo que necesit&aacute;s</strong>.</p>
                        <p>Nuestros servicios se alojan en los data centers de <strong>Amazon</strong>, garantiz&aacute;ndonos <strong>alta disponibilidad</strong> y brind&aacute;ndonos <strong>seguridad, escalabilidad y estabilidad.</strong></p>
                        <p>Utilizamos herramientas de programaci&oacute;n que nos permiten <strong>menores tiempo de planificaci&oacute;n, desarrollo y correcci&oacute;n</strong>, siguiendo los <strong>est&aacute;ndares de calidad, seguridad y eficiencia</strong> en todas las etapas.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-services colorlib-bg-white">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center">Proycer Wisp&trade;</h2>
                            <p class="admin text-center"><span>ISP's</span></p>
                            <p class="text-center">Sistema de Gesti&oacute;n y Administraci&oacute;n para empresas proveedoras de internet,
                                televisi&oacute;n y/o telefon&iacute;a.</p>
                            <p class="text-center">
                                <a href="/servicios/wisp" class="btn btn-primary btn-outline with-arrow">Conocer<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>

                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center">Proycer Time&trade;</h2>
                            <p class="admin text-center"><span>Turnos</span></p>
                            <p class="text-center">Sistema de Gesti&oacute;n y Administraci&oacute;n de calendario, agenda y citas para
                                turnos de consultorios.</p>
                            <p class="text-center">
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>

                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center">Proycer Store&trade;</h2>
                            <p class="admin text-center"><span>Tienda</span></p>
                            <p class="text-center">Sistema de Gesti&oacute;n y Administraci&oacute;n de ventas y log&iacute;stica para tu
                                comercio. Ideal retail.</p>
                            <p class="text-center">
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>

                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center">Proycer Work&trade;</h2>
                            <p class="admin text-center"><span>Partes de Servicio</span></p>
                            <p class="text-center">Sistema de Gesti&oacute;n y Administraci&oacute;n de &oacute;rdenes de servicios, tareas y/o trabajos.</p>
                            <p class="text-center">
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>

                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center">Proycer Help&trade;</h2>
                            <p class="admin text-center"><span>Soporte</span></p>
                            <p class="text-center">Sistema de Tickets y Soporte para tus servicios o proyectos. M&aacute;s cerca de tus clientes.</p>
                            <p class="text-center">
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>

                    <div class="col-md-4 animate-box">
                        <article>
                            <h2 class="text-center">Proycer Web&trade;</h2>
                            <p class="admin text-center"><span>Sitio Web</span></p>
                            <p class="text-center">Sistema Web autogestionable. Excelente para mantener tu sitio actualizado a bajo costo.</p>
                            <p class="text-center">
                                <a href="#" class="btn btn-primary btn-outline with-arrow">Pr&oacute;ximamente<i class="icon-arrow-right3"></i></a>
                            </p>
                        </article>
                    </div>
                </div>
            </div>
        </div>

        <div id="colorlib-subscribe" class="colorlib-subscribe">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 text-center colorlib-heading animate-box fadeInUp animated-fast">
                        <h2>Empez&aacute; a vender m&aacute;s y mejor ;)</h2>
                        <p>Dejanos tu email o n&uacute;mero de tel&eacute;fono y te contactamos para guiarte sin compromiso <br /> (no te a&ntilde;adimos a ninguna lista de correos)</p>
                    </div>
                </div>
                <div class="row animate-box fadeInUp animated-fast">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="row">
                            <div class="col-md-12">
                                <form class="form-inline qbstp-header-subscribe" method="post">
                                    <div class="col-three-forth">
                                        <div class="form-group">
                                            <input type="email" class="form-control" name="email" id="email" placeholder="Escrib&iacute; tu email o n&uacute;mero de tel&eacute;fono" required>
                                        </div>
                                    </div>
                                    <div class="col-one-third">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Enviar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php include __DIR__ . '/../inc/footer.phtml' ?>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
    <script src="/src/js/jquery.min.js"></script>
    <script src="/src/js/jquery.easing.1.3.js"></script>
    <script src="/src/js/bootstrap.min.js"></script>
    <script src="/src/js/jquery.waypoints.min.js"></script>
    <script src="/src/js/main.js"></script>
    <script>
        new Typed('#titulo', {
            strings: ['Servicios'],
            typeSpeed: 100,
            showCursor: false,
            startDelay: 200
        })
    </script>

</body>

</html>
