<?php include __DIR__ . '/../inc/header.phtml' ?>

<body>

    <div id="page">

        <?php include __DIR__ . '/../inc/navbar.phtml' ?>

        <section id="home" class="video-hero">
            <div class="overlay"></div>
            <div class="display-t display-t2 text-center">
                <div class="display-tc display-tc2">
                    <div class="container">
                        <div class="col-md-12 col-md-offset-0">
                            <div class="animate-box">
                                <h2 id="titulo"></h2>
                                <br /><br />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="colorlib-featured">
            <div class="row animate-box">
                <div class="featured-wrap">
                    <div class="owl-carousel">
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/escritorio-1.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/escritorio-2.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-md-8 col-md-offset-2">
                                <div class="featured-entry">
                                    <img class="img-responsive" src="/src/images/escritorio-3.png" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-work-featured colorlib-bg-white">
            <div class="container">
                <div class="row mobile-wrap">
                    <div class="col-md-5 animate-box fadeInUp animated-fast">
                        <div class="mobile-img" style="background-image: url(/src/images/movil-1.png);"></div>
                    </div>
                    <div class="col-md-7 animate-box fadeInUp animated-fast">
                        <div class="desc">
                            <h2>Todo en uno</h2>
                            <div class="features">
                                <span class="icon"><i class="icon-lightbulb"></i></span>
                                <div class="f-desc">
                                    <p>Con <strong>Proycer Wisp&trade;</strong> vas a poder gestionar el flujo de trabajo completo de tu empresa desde un sitio centralizado.</p>
                                </div>
                            </div>
                            <div class="features">
                                <span class="icon"><i class="icon-circle-compass"></i></span>
                                <div class="f-desc">
                                    <p>Carg&aacute; clientes, gener&aacute; facturas, revis&aacute; el estado de tu empresa incluso desde tu dispositivo m&oacute;vil.</p>
                                </div>
                            </div>
                            <div class="features">
                                <span class="icon"><i class="icon-beaker"></i></span>
                                <div class="f-desc">
                                    <p>Todo el poder de un sistema de gesti&oacute;n a tu alcance, con las funcionalidades que necesit&aacute;s para registrar &oacute;rdenes de servicio, nuevas instalaciones, bajas de clientes, cobrar facturas y m&aacute;s.</p>
                                </div>
                            </div>
                            <p><a href="#precios" class="btn btn-primary btn-outline with-arrow">Quiero ver los precios <i class="icon-arrow-right3"></i></a></p>
                        </div>
                    </div>
                </div>
                <div class="row mobile-wrap">
                    <div class="col-md-5 col-md-push-7 animate-box fadeInUp animated-fast">
                        <div class="mobile-img" style="background-image: url(/src/images/movil-2.png);"></div>
                    </div>
                    <div class="col-md-7 col-md-pull-5 animate-box fadeInUp animated-fast">
                        <div class="desc">
                            <h2>Trabaj&aacute; en movimiento</h2>
                            <div class="features">
                                <span class="icon"><i class="icon-lightbulb"></i></span>
                                <div class="f-desc">
                                    <p>Carg&aacute; clientes, gener&aacute; facturas, revis&aacute; el estado de tu empresa incluso desde tu dispositivo m&oacute;vil.</p>
                                </div>
                            </div>
                            <div class="features">
                                <span class="icon"><i class="icon-circle-compass"></i></span>
                                <div class="f-desc">
                                    <p><b>Proycer Wisp&trade;</b> es adaptable y multiplataforma.</p>
                                </div>
                            </div>
                            <div class="features">
                                <span class="icon"><i class="icon-beaker"></i></span>
                                <div class="f-desc">
                                    <p>Con diferentes permisos de acceso, vas a poder gestionar y ver la informaci&oacute;n que necesit&aacute;s, vos, tus empleados o tus clientes.</p>
                                </div>
                            </div>
                            <p><a href="#precios" class="btn btn-primary btn-outline with-arrow">Quiero ver los precios <i class="icon-arrow-right3"></i></a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="colorlib-pricing">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box fadeInUp animated-fast">
                        <h2 id="precios">Planes</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 text-center animate-box fadeInUp animated-fast">
                        <div class="pricing">
                            <h2 class="pricing-heading">Inicio</h2>
                            <p>Hasta <b>300</b> clientes.<br />Actualizaciones autom&aacute;ticas.<br />Soporte por Telegram.<br />Documentaci&oacute;n.</p>
                            <p><a href="#" class="btn btn-primary" data-toggle="modal" data-target="#contratar">Contratar</a></p>
                        </div>
                    </div>
                    <div class="col-md-3 text-center animate-box fadeInUp animated-fast">
                        <div class="pricing">
                            <h2 class="pricing-heading">B&aacute;sico</h2>
                            <p>Hasta <b>600</b> clientes.<br />Actualizaciones autom&aacute;ticas.<br />Soporte por Telegram.<br />Documentaci&oacute;n.</p>
                            <p><a href="#" class="btn btn-primary" data-toggle="modal" data-target="#contratar">Contratar</a></p>
                        </div>
                    </div>
                    <div class="col-md-3 text-center animate-box fadeInUp animated-fast">
                        <div class="pricing">
                            <h2 class="pricing-heading">Avanzado</h2>
                            <p>Hasta <b>1000</b> clientes.<br />Actualizaciones autom&aacute;ticas.<br />Soporte por Telegram.<br />Documentaci&oacute;n.</p>
                            <p><a href="#" class="btn btn-primary" data-toggle="modal" data-target="#contratar">Contratar</a></p>
                        </div>
                    </div>
                    <div class="col-md-3 text-center animate-box fadeInUp animated-fast">
                        <div class="pricing">
                            <h2 class="pricing-heading">Ilimitado</h2>
                            <p><b>Ilimitados</b> clientes.<br />Actualizaciones autom&aacute;ticas.<br />Soporte por Telegram.<br />Documentaci&oacute;n.</p>
                            <p><a href="#" class="btn btn-primary" data-toggle="modal" data-target="#contratar">Contratar</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php include __DIR__ . '/../inc/footer.phtml' ?>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
    </div>

    <div class="modal fade" id="contratar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Solicitar Servicio</h4>
                </div>
                <div class="modal-body">
                    <form action="/contrato" method="post">
                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="text" id="nombre" name="nombre" class="form-control" placeholder="Nombre completo" required>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="text" id="contacto" name="contacto" class="form-control" placeholder="Email o tel&eacute;fono de contacto" required>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <select class="form-control" name="plan" required>
                                    <option value="inicio">Inicio / 300 clientes</option>
                                    <option value="basico">B&aacute;sico / 600 clientes</option>
                                    <option value="avanzado">Avanzado / 1000 clientes</option>
                                    <option value="ilimitado">Ilimitado / ilimitados clientes</option>
                                </select>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            <input type="submit" value="Solicitar!" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="/src/js/jquery.min.js"></script>
    <script src="/src/js/jquery.easing.1.3.js"></script>
    <script src="/src/js/bootstrap.min.js"></script>
    <script src="/src/js/owl.carousel.min.js"></script>
    <script src="/src/js/jquery.waypoints.min.js"></script>
    <script src="/src/js/main.js"></script>
    <script>
        $(document).ready(function() {
            var owl = $('.owl-carousel');
            owl.owlCarousel({
                animateOut: 'fadeOut',
                animateIn: 'fadeIn',
                autoplay: true,
                items: 1,
                loop: true,
                margin: 0,
                responsiveClass: true,
                nav: true,
                dots: false,
                autoplayHoverPause: false,
                smartSpeed: 1000,
                navText: [
                    "<i class='icon-arrow-left3 owl-direction'></i>",
                    "<i class='icon-arrow-right3 owl-direction'></i>"
                ]
            });

            new Typed('#titulo', {
                strings: ['Proycer Wisp'],
                typeSpeed: 100,
                showCursor: false,
                startDelay: 200
            })
        });
    </script>
</body>

</html>
